### ISSUE TITLE
"Failed to notify build listener." and "Found 0 tasks"

### ISSUE THREAD

**Issue by chik4ge** [microsoft/vscode-gradle#1331]
Extension Name: vscode-gradle
Extension Version: v3.12.7
OS Version: Ubuntu 22.04.2 LTS
VSCode version: 1.78.0-insider

**Describe the bug**
Some gradle tasks do not appear in tab.

**To Reproduce**
- [Clone this repository](https://github.com/chik4ge/MineExporteR)
- Open in vscode
- Check output of "Gradle for Java"

**Expected behavior**
No errors thrown.

**Screenshots**

**Output from "Gradle for Java"**
```
[debug] Refreshing tasks
[info] Java Home: /usr/lib/jvm/java-8-openjdk-amd64
[info] JVM Args: -Xmx3G,-Dfile.encoding=UTF-8,-Duser.country=JP,-Duser.language=ja,-Duser.variant
[info] Gradle User Home: /home/chikage/.gradle
[info] Gradle Version: 4.10.3
[info] > Configure project :
New Dep: net.minecraftforge:forge:1.12.2-14.23.5.2855_mapped_stable_39-1.12

CONFIGURE SUCCESSFUL in 1s

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> org/gradle/plugins/ide/internal/tooling/model/DefaultGradleProject

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[error] Error getting build for /home/chikage/dev/_Minecraft/MineExporteR: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
[info] Found 0 tasks
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
```

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**
All `./gradlew` commands from terminal works fine.

**Comment by macjabeth** [comment]
I'm also seeing this error.

**Comment by haschulz** [comment]
same applies for me
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'.
[error] Error getting build for /Users/xxx: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'.
[info] Java Home: /Users/xxx/.sdkman/candidates/java/8.0.362-zulu/zulu-8.jdk/Contents/Home
[info] JVM Args: -XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=DE,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /Users/xxx/.gradle
[info] Gradle Version: 3.5
[info] CONFIGURE SUCCESSFUL

**Comment by justadirck** [comment]
this is my world right now

**Comment by VRRAF** [comment]
This change in commit breaks compatibility with Gradle < v5.0
https://github.com/microsoft/vscode-gradle/blob/8ebc46f89a28a0ef5c8a1f91df95939082423be5/gradle-plugin/src/main/java/com/microsoft/gradle/GradleProjectModelBuilder.java#L45

This class is available in Gradle > v5.0

In Gradle < v5.0 there is https://github.com/gradle/gradle/blob/b9a962bf70638332300e7f810689cb2febbd4a6c/subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/gradle/DefaultGradleProject.java , but I don't know if it's compatible. 

```
[info] Java Home: C:\JDKs\Adoptium\jdk8u322-b06
[info] JVM Args: -XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\xxx\.gradle
[info] Gradle Version: 4.10.3
[info] > Configure project :
New Dep: net.minecraftforge:forge:1.12.2-14.23.5.2855_mapped_stable_39-1.12

CONFIGURE SUCCESSFUL in 1s
[error] FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> org/gradle/plugins/ide/internal/tooling/model/DefaultGradleProject

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener.
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy16.buildFinished(Unknown Source)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:154)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:122)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:88)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:84)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:84)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:64)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:42)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:61)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: org/gradle/plugins/ide/internal/tooling/model/DefaultGradleProject
	at com.microsoft.gradle.GradleProjectModelBuilder.buildAll(GradleProjectModelBuilder.java:68)
	at org.gradle.tooling.internal.provider.runner.DefaultBuildController.getModel(DefaultBuildController.java:79)
	at org.gradle.tooling.internal.consumer.connection.ParameterAwareBuildControllerAdapter.getModel(ParameterAwareBuildControllerAdapter.java:39)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:113)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:76)
	at org.gradle.tooling.internal.consumer.connection.UnparameterizedBuildController.getModel(UnparameterizedBuildController.java:61)
	at com.microsoft.gradle.api.GradleModelAction.execute(GradleModelAction.java:12)
	at com.microsoft.gradle.api.GradleModelAction.execute(GradleModelAction.java:9)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:64)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.buildResult(ClientProvidedBuildActionRunner.java:77)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.access$000(ClientProvidedBuildActionRunner.java:37)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner$1.buildFinished(ClientProvidedBuildActionRunner.java:56)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:370)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:352)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:340)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:327)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	... 71 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[error] Error getting build for C:\dvlp\test\MineExporteR: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
[info] Found 0 tasks
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
```

**Comment by zoladkow** [comment]
Same issue, the projects seems to open up fine, some initialization goes on and finishes successfully, then there is this message stating that "Could not run build action using connection to Gradle distribution [...]"

I tried setting the properties, to avoid using wrapper and use a distribution of 3.5 i installed locally, but the message stays the same.

My current settings:
```
{
    "gradle.nestedProjects": false,
    "gradle.debug": true,
    "java.import.gradle.version": "3.5",
    "java.import.gradle.home": "C:\\Soft\\gradle-3.5",
    "java.import.gradle.java.home": "C:\\Soft\\java\\temurin\\jdk8u382-b05",
    "java.import.gradle.wrapper.enabled": false,
    "java.compile.nullAnalysis.mode": "disabled"
}
```


```
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: c:\Users\bartosz.zoladkowski\.vscode\extensions\vscjava.vscode-gradle-3.12.7\lib\gradle-server.bat 63719
[info] [gradle-server] Server started, listening on 63719
[info] Gradle client connected to server
[debug] Refreshing tasks
[info] Java Home: C:\Soft\java\temurin\jdk8u382-b05
[info] JVM Args: -XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\bartosz.zoladkowski\.gradle
[info] Gradle Version: 3.5
[info] CONFIGURE SUCCESSFUL

Total time: 17.188 secs
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.
[error] Error getting build for c:\p\pg\mmrc-vscode: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.
[info] Java Home: C:\Soft\java\temurin\jdk8u382-b05
[info] JVM Args: -XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\bartosz.zoladkowski\.gradle
[info] Gradle Version: 3.5
[info] CONFIGURE SUCCESSFUL

Total time: 1.175 secs
[error] [gradle-server] Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.
[error] Error getting build for c:\p\pg\mmrc-vscode: Could not run build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.
[info] Found 0 tasks
```


And a bit offtopic, but what is causing a `bin` directory to appear? This isn't the Gradle convention, it should be a `build` directory instead. Is there a setting that can control this? I can imagine it's some other extension, as the Gradle for Java has the above problem, so no actual build is happening using Gradle yet.

**Comment by jessejyang** [comment]
I also got same issue, downgrading to v3.7.0 resolved it for me.

**Comment by jordanorc** [comment]
Same problem here...

**Comment by Danman40th** [comment]
I'm not sure what I'm asked to do but I'm trying to learn how to do
anything anyone can show me I'm bad dyslexic, so it makes It hard to learn
any of this.

**Comment by VRRAF** [comment]
@jdneo and @CsCherrYY sorry for tagging you directly.

#1302  pull request broke compatibility with gradle version < 5 

As I commented above, the vscode-gradle project seems to be incompatible for gradle projects based on version < 5 .
If a fix is not planned, at least it would be nice to update the requirements of the vscode-gradle extension.

**Comment by DesolateIntention** [comment]
Downgrading to 3.12.5 fixed it when using Gradle 4.9.
