### ISSUE TITLE
Language Server startup not handling distributionURL set to local file in gradle-wrapper.properties

### ISSUE THREAD

**Issue by crt-31** [microsoft/vscode-gradle#1332]
Extension Name: vscode-gradle
Extension Version: 3.12.7
OS Version: Win 10
VSCode version: 1.76

**Describe the bug**
Plugin is not loading and throwing errors when trying to use a local file distributionUrl in the gradle-wrapper.properties. 
For instance, I set the `distributionUrl=file:///C:/gradledists/gradle-7.3.3-bin.zip`

Then I see exceptions in "Gradle for Java (Language Server)":
`java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/gradledists/gradle-7.3.3-bin.zip`

Note, I am using this on an airgap (no internet) environment. 

**To Reproduce**
in gradle-wrapper.properties, set distributionUrl to a URL to a local file.

**Expected behavior**
Should be able to set distributionUrl to a local file.

**Screenshots**

**Output from "Gradle for Java"**

> Apr 13, 2023 11:04:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
> SEVERE: Internal error: java.lang.reflect.InvocationTargetException
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
> 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
> 	... 11 more
> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/gradledists/gradle-7.3.3-bin.zip
> 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
> 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
> 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
> 	at java.base/java.nio.file.Path.of(Path.java:147)
> 	at java.base/java.nio.file.Paths.get(Paths.java:69)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.getWrapperPropertiesInfo(GradleLibraryResolver.java:185)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.resolveGradleAPI(GradleLibraryResolver.java:107)
> 	at com.microsoft.gradle.GradleServices.applySetting(GradleServices.java:168)
> 	at com.microsoft.gradle.GradleLanguageServer.initialize(GradleLanguageServer.java:82)
> 	... 16 more
> 
> [Error - 11:04:16 PM] Server initialization failed.
>   Message: Internal error.
>   Code: -32603 
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
> 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
> 	... 11 more
> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/gradledists/gradle-7.3.3-bin.zip
> 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
> 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
> 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
> 	at java.base/java.nio.file.Path.of(Path.java:147)
> 	at java.base/java.nio.file.Paths.get(Paths.java:69)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.getWrapperPropertiesInfo(GradleLibraryResolver.java:185)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.resolveGradleAPI(GradleLibraryResolver.java:107)
> 	at com.microsoft.gradle.GradleServices.applySetting(GradleServices.java:168)
> 	at com.microsoft.gradle.GradleLanguageServer.initialize(GradleLanguageServer.java:82)
> 	... 16 more
> 
> [Error - 11:04:16 PM] Starting client failed
>   Message: Internal error.
>   Code: -32603 
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
> 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
> 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
> 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
> 	... 11 more
> Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/gradledists/gradle-7.3.3-bin.zip
> 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
> 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
> 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
> 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
> 	at java.base/java.nio.file.Path.of(Path.java:147)
> 	at java.base/java.nio.file.Paths.get(Paths.java:69)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.getWrapperPropertiesInfo(GradleLibraryResolver.java:185)
> 	at com.microsoft.gradle.resolver.GradleLibraryResolver.resolveGradleAPI(GradleLibraryResolver.java:107)
> 	at com.microsoft.gradle.GradleServices.applySetting(GradleServices.java:168)
> 	at com.microsoft.gradle.GradleLanguageServer.initialize(GradleLanguageServer.java:82)
> 	... 16 more

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by tcfurrer** [comment]
Duplication of #1615. See solution there.
