### ISSUE TITLE
Performance issue when enabling Build Server

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-gradle#1441]
See: https://github.com/redhat-developer/vscode-java/issues/3357

              Wow, so slowly. I have to wait 30 minutes after opening the project for it to run. I don't know the cause yet, I hope the development team soon finds the cause.

![image](https://github.com/redhat-developer/vscode-java/assets/51206070/d981e84d-bf97-450f-9998-2c6338dec98c)

_Originally posted by @alexanderloong in https://github.com/redhat-developer/vscode-java/issues/3357#issuecomment-1776494511_

**Comment by jdneo** [comment]
One thing we can explore is to avoid Gradle building the workspace right after import. Instead, let it build before launch/test

**Comment by alexanderloong** [comment]
Thanks, my problem has been resolved. People can go into setting and choose it.
![image](https://github.com/redhat-developer/vscode-java/assets/51206070/9bfc9b84-65b0-441d-b5bd-1524562241d1)

**Comment by mbruce** [comment]
This is still the #1 issue with this plugin. I have a project I can open in IntelliJ in a few minutes. But it's over an hour every time in vscode. It's completely unusable.

**Comment by Yazington** [comment]
2024 and this is still an issue

**Comment by mbruce** [comment]
> 2024 and this is still an issue

Yep, still terribly slow.

**Comment by mbruce** [comment]
Keeping this alive.  Still terribly slow.

**Comment by jdneo** [comment]
@mbruce Have you tried the pre-release version?

**Comment by mbruce** [comment]
yes, confirmed just now that it's still extremely slow with the
prerelease.  over an hour and it's still initializing.  this will
eventually complete.

**Comment by jdneo** [comment]
@mbruce Could you share the server log? Run `Java: Open Java Language Server Log File`

**Comment by devondragon** [comment]
[log.txt](https://github.com/user-attachments/files/17847102/log.txt)

@jdneo  - I'm having the same issue and here is my log file while it's slowly loading

**Comment by devondragon** [comment]
FWIW I am not having this issue with VS Code Insiders, just the main VS Code release version.

**Comment by jdneo** [comment]
> FWIW I am not having this issue with VS Code Insiders, just the main VS Code release version.

@devondragon I'm shocked that they perf can be different between vscode release and insiders. Is there any setup difference between two? For example, different extensions are installed?

**Comment by cristatus** [comment]
For me, this is happening when I import a project with `includeBuild` to another project. To me the issue seems to be JDK incompatibility. The project required JDK 11 and somehow the plugin fails to use JDK 11 for included project.

**Comment by rgrunber** [comment]
in vscode-java, there are setting that are set to `auto`, which means disabled by default in VS Code, but enabled in VS Code Insiders (they're experimental settings we wish to enable by default eventually) !

I was just investigating https://github.com/redhat-developer/vscode-java/issues/3904 and one odd behaviour I ran into was that if "Gradle for Java" was installed, after the first "Java: Clean Language Server Workspace" command, all other reloads of the window caused the index to be rebuilt every time. The project itself was Maven and unrelated to Gradle. Either way this shouldn't happen as nothing has changed. At first I never ran into this because I always ran with `java.sharedIndexes.enabled": "on"`, but this setting has an `auto` value which means it behaves differently in the Insiders release.

@devondragon , does setting `java.sharedIndexes.enabled": "on"` improve performance for you ? There's still probably something else going on because I the build finishes every time but worth a try.

**Comment by devondragon** [comment]
That seems to improve things considerably!  Thanks!!

**Comment by rgrunber** [comment]
I think I found another problem. Probably the root one. https://github.com/microsoft/vscode-gradle/blob/86a76e9389e1736eb15d21a5e2a1276fa41cd2bb/extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/java/builder/BuildStateManager.java#L73

vscode-gradle is contributing a participant under the id `org.eclipse.jdt.core`. But jdt.core has its own participant that you're kicking out 😛 . See https://github.com/eclipse-jdt/eclipse.jdt.core/blob/4d5b78631454da002130f609615dcca34b635574/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L5448. So what does the jdt.core participant do ? Oh not much, just making sure the external library timestamps get saved correctly : https://github.com/eclipse-jdt/eclipse.jdt.core/blob/4d5b78631454da002130f609615dcca34b635574/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L4709 ➡  https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java#L4797-L4798 . Without that they aren't saved, and later on we re-index the library because the old timetsamp is nowhere to be found, but the new one exists : https://github.com/eclipse-jdt/eclipse.jdt.core/blob/4d5b78631454da002130f609615dcca34b635574/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/DeltaProcessor.java#L1067-L1069 . Luckily this seems like an easy fix.

(Oh, and disabling vscode-gradle isn't enough to make the problem go away because we use `extensions.all` when collecting contributions on the vscode-java side, and that doesn't seem to exclude disabled/uninstalled extensions)

**Comment by mbruce** [comment]
no luck for me with that setting.  still takes forever to index, and sits on 32% for at least an hour.

**Comment by mbruce** [comment]
Still the top issue for this plugin.  At least an hour on every startup.

**Comment by telus-urooz** [comment]
Bumping this up. This still happens. IntelliJ is ready withing minutes for a big java project but this extension takes forever even when I have disabled all other extensions and this is the only one enabled. I also disabled the gradle but still the same performance

`{
  message: 'Removing old folder in globalStorage : 1.43.1',
  level: 'info',
  timestamp: '2025-07-02 12:34:08.992'
}
{
  message: "Use the JDK from 'java.jdt.ls.java.home' setting as the initial default project JDK.",
  level: 'info',
  timestamp: '2025-07-02 12:34:09.084'
}
{
  message: 'Starting Java server with: C:\\Users\\x263290\\.jdks\\corretto-21.0.7\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseG1GC -XX:+UseStringDeduplication -Dsun.zip.disableMemoryMapping=true -Xmx12G -Xms1G -Xlog:disable -javaagent:c:\\Users\\x263290\\.vscode\\extensions\\redhat.java-1.44.2025070208-win32-x64\\lombok\\lombok-1.18.39-4050.jar -jar c:\\Users\\x263290\\.vscode\\extensions\\redhat.java-1.44.2025070208-win32-x64\\server\\plugins\\org.eclipse.equinox.launcher_1.7.0.v20250519-0528.jar -configuration c:\\Users\\x263290\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\1.44.2025070208\\config_ss_win -data c:\\Users\\x263290\\AppData\\Roaming\\Code\\User\\workspaceStorage\\626f93e864d67b95f9c602b5747e9d8d\\redhat.java\\ss_ws',
  level: 'info',
  timestamp: '2025-07-02 12:34:10.189'
}
{
  message: 'Starting Java server with: C:\\Users\\x263290\\.jdks\\corretto-21.0.7\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -DDetectVMInstallationsJob.disabled=true -Dfile.encoding=utf8 -XX:+UseG1GC -XX:+UseStringDeduplication -Dsun.zip.disableMemoryMapping=true -Xmx12G -Xms1G -Xlog:disable -javaagent:c:\\Users\\x263290\\.vscode\\extensions\\redhat.java-1.44.2025070208-win32-x64\\lombok\\lombok-1.18.39-4050.jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\\Users\\x263290\\AppData\\Roaming\\Code\\User\\workspaceStorage\\626f93e864d67b95f9c602b5747e9d8d\\redhat.java -Daether.dependencyCollector.impl=bf -Djdt.core.sharedIndexLocation=C:\\Users\\x263290\\AppData\\Roaming\\.jdt\\index -jar c:\\Users\\x263290\\.vscode\\extensions\\redhat.java-1.44.2025070208-win32-x64\\server\\plugins\\org.eclipse.equinox.launcher_1.7.0.v20250519-0528.jar -configuration c:\\Users\\x263290\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\1.44.2025070208\\config_win -data c:\\Users\\x263290\\AppData\\Roaming\\Code\\User\\workspaceStorage\\626f93e864d67b95f9c602b5747e9d8d\\redhat.java\\jdt_ws',
  level: 'info',
  timestamp: '2025-07-02 12:34:10.231'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.vector\r\n',
  level: 'info',
  timestamp: '2025-07-02 12:34:10.477'
}
{
  message: 'Jul 02, 2025 12:34:12 PM org.apache.aries.spifly.BaseActivator log\r\n' +
    'INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\r\n',
  level: 'info',
  timestamp: '2025-07-02 12:34:12.805'
}
{
  message: '[Warn  - 12:34:28 PM] Jul 2, 2025, 12:34:28 PM Could not load Gradle version information\n' +
    'Cannot download published Gradle versions.\n' +
    'org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.\r\n' +
    '\tat org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:167)\r\n' +
    '\tat org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:151)\r\n' +
    '\tat org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.create(PublishedGradleVersions.java:111)\r\n' +
    '\tat org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:73)\r\n' +
    '\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\r\n' +
    'Caused by: java.net.SocketTimeoutException: Connect timed out\r\n' +
    '\tat java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)\r\n' +
    '\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)\r\n' +
    '\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n' +
    '\tat java.base/java.net.Socket.connect(Socket.java:751)\r\n' +
    '\tat java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)\r\n' +
    '\tat java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)\r\n' +
    '\tat java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)\r\n' +
    '\tat java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)\r\n' +
    '\tat java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)\r\n' +
    '\tat java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)\r\n' +
    '\tat java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)\r\n' +
    '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)\r\n' +
    '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)\r\n' +
    '\tat java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)\r\n' +
    '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)\r\n' +
    '\tat java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)\r\n' +
    '\tat java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)\r\n' +
    '\tat org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:164)\r\n' +
    '\t... 4 more\r\n',
  level: 'info',
  timestamp: '2025-07-02 12:34:28.177'
}
`


`!SESSION 2025-07-02 12:34:10.974 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.7
java.vendor=Amazon.com Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  --pipe=\\.\pipe\lsp-d03fca8591f05a38804355be23e90fce-sock
Command-line arguments:  -data c:\Users\x263290\AppData\Roaming\Code\User\workspaceStorage\626f93e864d67b95f9c602b5747e9d8d\redhat.java\jdt_ws --pipe=\\.\pipe\lsp-d03fca8591f05a38804355be23e90fce-sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:16.247
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:17.370
!MESSAGE Started org.eclipse.buildship.core 238ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:17.375
!MESSAGE Started org.eclipse.m2e.core 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:18.365
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:18.534
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:18.539
!MESSAGE Initializing Java Language Server 1.49.0.202507020805

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.464
!MESSAGE ProjectRegistryRefreshJob finished 2084ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.843
!MESSAGE Setting C:\Users\x263290\.jdks\corretto-21.0.7 as 'JavaSE-21' environment (id:1751474059767)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.864
!MESSAGE Setting C:\Users\x263290\.jdks\corretto-11.0.22 as 'JavaSE-11' environment (id:1751474059848)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.883
!MESSAGE Setting C:\Users\x263290\.jdks\corretto-17.0.14 as 'JavaSE-17' environment (id:1751474059867)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.887
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.917
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.920
!MESSAGE Non-Static Commands: [java.project.import, java.project.changeImportedProjects, java.navigate.openTypeHierarchy, java.project.resolveStackTraceLocation, java.edit.handlePasteEvent, java.edit.stringFormatting, java.project.getSettings, java.project.resolveWorkspaceSymbol, java.project.upgradeGradle, java.project.createModuleInfo, java.vm.getAllInstalls, java.edit.organizeImports, java.project.refreshDiagnostics, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.updateSettings, java.project.getAll, java.reloadBundles, java.project.isTestFile, java.project.resolveText, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.smartSemicolonDetection, java.project.updateSourceAttachment, java.project.updateClassPaths, java.decompile, java.protobuf.generateSources, java.project.resolveSourceAttachment, java.project.updateJdk, java.project.addToSourcePath, java.completion.onDidSelect]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.953
!MESSAGE RepositoryRegistryUpdateJob finished 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:19.993
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:34:25.153
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.buildship.core 2 0 2025-07-02 12:34:28.172
!MESSAGE Could not load Gradle version information
!STACK 0
org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:167)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:151)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.create(PublishedGradleVersions.java:111)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:164)
	... 4 more

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:49:07.063
!MESSAGE Workspace initialized in 887109ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-07-02 12:49:07.078
!MESSAGE >> initialization job finished
`

**Comment by mbruce** [comment]
Keeping this bug report alive.  Still the top issue for this plugin. At least an hour on every startup.
