### ISSUE TITLE
I used Java 21 but it said I was using Java 11

### ISSUE THREAD

**Issue by wifi-left** [microsoft/vscode-gradle#1485]
Extension Name: vscode-gradle
Extension Version:
OS Version: Windows 11
VSCode version: 1.88.1

**Describe the bug**
I used Java 21 but it said I was using Java 11
```
Caused by: java.lang.UnsupportedOperationException: You are using an outdated version of Java (11). Java 17 or higher is required.
The JAVA_HOME environment variable is currently set to (D:\OPENJDK\jdk-21\).
	at net.fabricmc.loom.bootstrap.LoomGradlePluginBootstrap.validateEnvironment(LoomGradlePluginBootstrap.java:66)
	at net.fabricmc.loom.bootstrap.LoomGradlePluginBootstrap.apply(LoomGradlePluginBootstrap.java:30)
	at net.fabricmc.loom.bootstrap.LoomGradlePluginBootstrap.apply(LoomGradlePluginBootstrap.java:15)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
	... 166 more
```

Command out put for `D:\OPENJDK\jdk-21\bin\java.exe --version`:
```
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Microsoft-8905927 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Microsoft-8905927 (build 21.0.2+13-LTS, mixed mode, sharing)
```

**To Reproduce**
Create a fabric-loom project (for Minecraft 1.20.5)
Open the project.
Go to the debug output of `Build Server for Gradle (log)`
See the error

**Expected behavior**
Import the project correctly

**Screenshots**
Notice: GUI language: Chinese
![image](https://github.com/microsoft/vscode-gradle/assets/63381531/a634039c-37be-4cfe-a831-f153430295cb)

**Output from "Gradle for Java"**
```
[info] [gradle-server] Server started, listening on 21913
[info] Gradle client connected to server
[info] Java Home: D:\OPENJDK\jdk-21
[info] JVM Args: --add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1G,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant
[info] Gradle User Home: C:\Users\Gamom\.gradle
[info] Gradle Version: 8.7
[info] > Configure project :
Fabric Loom: 1.6.11

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

CONFIGURE SUCCESSFUL in 13s
[info] Found 86 tasks
```

**Does the bug still exist if you disable all other extensions?**
No

**Additional context**
Only happens when I turned on `Java > Gradle > Build Server: Enable`

```[tasklist]
### Tasks
```

**Comment by wifi-left** [comment]
Solved when I update the plugin.
