### ISSUE TITLE
gradle java project gives errors when parameters passed to gradle process

### ISSUE THREAD

**Issue by skaluva** [microsoft/vscode-gradle#1529]
Extension Name: vscode-gradle
Extension Version: 3.15.0
OS Version: Windows 11
VSCode version: 1.91.0

**Describe the bug**
I have a simple gradle project which uses gradle version **7.5.1** and java version **JDK 17**. I have custom gradle plugin in build.gradle which expects **-PMY_PARAM=abc** to be passed when gradle commands gets executed on the project. For example:
from command line i have to pass like this: **gradle build -PMY_PARAM=ABC** to make the build successful. This need to be passed for all tasks. Same i'm trying to achieve in vscode using vscode-gradle extension but im failed to do that despite all trials. Below is my **settings.json** 

```java
{
    "java.import.gradle.home": "C:\\XYZ\\gradle-git-7.5.1",
    "java.import.gradle.user.home": "C:\\Users\\XYZ\\.gradle751",
    "java.import.gradle.version": "",
    "java.import.gradle.wrapper.enabled": false,
    //"java.gradle.buildServer.enabled":"off",
    "java.import.gradle.java.home": "C:\\XYZ\\zulu17.46.20-sa-jdk17.0.9-win_x64",
    "java.jdt.ls.java.home": "C:\\XYZ\\zulu17.46.20-sa-jdk17.0.9-win_x64",
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-1.7",
        "path": "C:\\Program Files\\Zulu\\zulu-7",
      },
      {
        "name": "JavaSE-1.8",
        "path": "C:\\XYZ\\jdk1.8.0_271"
      },
      {
        "name": "JavaSE-11",
        "path": "C:\\XYZ\\zulu11.60.20-sa-jdk11.0.17-win_x64",
      },
      {
        "name": "JavaSE-17",
        "path": "C:\\XYZ\\zulu17.46.20-sa-jdk17.0.9-win_x64",
        "default": true
      }
    ],
    "gradle.nestedProjects": true,
    "security.workspace.trust.untrustedFiles": "open",
    "workbench.iconTheme": "vscode-icons",
    "java.jdt.ls.vmargs": "",
    "java.import.gradle.jvmArguments": "-PMY_PARAM=abc", //tried here, it works during 'gradle configure' stage but java project initialization fails with below error
    "java.import.gradle.arguments": "", //i tried adding the same here but its not getting passed to gradle commands and so gradle tasks execution failing with errors as that prop not found.
    "terminal.integrated.copyOnSelection": true,
    "workbench.settings.applyToAllProfiles": [
      "terminal.integrated.copyOnSelection"
    ],
    "maven.executable.path": "C:\\XYZ\\apache-maven-3.6.3\\bin\\mvn.cmd",
    "maven.executable.preferMavenWrapper": false
    }
``` 
If i pass param to `java.import.gradle.jvmArguments` getting below error:

```java
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html
Process command line: C:\\XYZ\softwares\zulu17.46.20-sa-jdk17.0.9-win_x64\bin\java.exe -PMY_PARAM=abc --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\\XYZ\softwares\gradle-git-7.5.1\lib\gradle-launcher-7.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1
Please read the following process output to find out more:
-----------------------
Unrecognized option: -PMY_PARAM=abc
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.microsoft.gradle.bs.importer.Utils.getBuildTargetsMappedByProjectPath(Utils.java:47)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importProjects(GradleBuildServerProjectImporter.java:266)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importToWorkspace(GradleBuildServerProjectImporter.java:179)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:164)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:126)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:277)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html
Process command line: C:\\XYZ\softwares\zulu17.46.20-sa-jdk17.0.9-win_x64\bin\java.exe -PMY_PARAM=abc --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\\XYZ\softwares\gradle-git-7.5.1\lib\gradle-launcher-7.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1
Please read the following process output to find out more:
-----------------------
Unrecognized option: -PMY_PARAM=abc
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


``` 

If i set the param to `"java.import.gradle.arguments": "-PMY_PARAM=abc"`, its not getting passed at all to gradle tasks causing gradle configure stage failures.

I'm banging my head to fix this for the past few weeks. I'm not sure how to get this done. I really wanted to use vscode for all my future projects. But these unknown errors blocking me. Please suggest.

**Comment by jdneo** [comment]
`java.import.gradle.arguments` and `java.import.gradle.jvmArguments` are used to import gradle project. They are not used when running gradle tasks.

Have you tried
![image](https://github.com/user-attachments/assets/1a2d3c87-5b08-4672-a0e0-bf5d38193f68)

**Comment by skaluva** [comment]
@jdneo Thanks for the reply. Actually im not executing any task manually. When i save the build.gradle or importing the project, vscode automatically running gradle tasks. Due to lack of that property, gradle configure stage itself failing (because my custom plugin expects it). Like i said if i set the property here ` java.import.gradle.jvmArguments`, gradle tasks are running successfully but java project errors are coming in vscode while creating as java project with the above exception. This is the log i see in gradle output console while running gradle tasks during project import or whenever build.gradle saved:
```java
[info] [gradle-server] Server started, listening on 64005
[info] Gradle client connected to server
[info] Java Home: C:\XYZ\softwares\zulu17.46.20-sa-jdk17.0.9-win_x64
[info] JVM Args: -PMY_PARAM=abc,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant

``` 

I see its getting passed as JVM args and so it just works for gradle tasks.

Later vscode trying to create as java project which is giving 'Java error'
![image](https://github.com/user-attachments/assets/877c4b62-4cc3-4294-be3f-1f76baf1114f)

When i checked log for the same, i see this exception:

```java
Process command line: C:\\XYZ\softwares\zulu17.46.20-sa-jdk17.0.9-win_x64\bin\java.exe -PMY_PARAM=abc --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\\XYZ\softwares\gradle-git-7.5.1\lib\gradle-launcher-7.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.5.1
Please read the following process output to find out more:
-----------------------
Unrecognized option: -PMY_PARAM=abc
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.microsoft.gradle.bs.importer.Utils.getBuildTargetsMappedByProjectPath(Utils.java:47)

``` 

Looks like this param getting passed to "java" process and there its failing with `Unrecognized option`. I tried one option like creating `gradle.properties` file and set that param. It worked for both gradle tasks and java project also created without any issues. But i would like to avoid this. If there is a setting in vscode itself, it helps.

**Comment by jdneo** [comment]
Looks like `java.import.gradle.arguments` is ignored, and `java.import.gradle.jvmArguments` is mis-used as the argument list.

I believe `-PMY_PARAM=abc` should be put into `java.import.gradle.arguments` since it's not a jvm arg. But the implementation is not in that way.

See: https://github.com/microsoft/vscode-gradle/blob/8e6e7ac008dd300ef18635ac140dad6f44a9bb0f/extension/src/client/GradleClient.ts#L256
https://github.com/microsoft/vscode-gradle/blob/8e6e7ac008dd300ef18635ac140dad6f44a9bb0f/extension/src/util/config.ts#L189

**Comment by skaluva** [comment]
Yes i felt the same. In fact, i was surprised why this `java.import.gradle.arguments`  is not honored. Thanks for acknowledging it. Can this be fixed?

**Comment by jdneo** [comment]
I've no concrete date for that now, I'm working on other stuffs recently which may not have enough time for this one in short future.

Contributions are welcome btw :)

**Comment by skaluva** [comment]
Oh.. okay.. no issues.. Im new to these contributions. Just forking the repository, making the relevant changes and testing .. raising merge requests .. is this the process or if you have any relevant documentation, i can look into it.. thanks in advance.. :)

Edit: Ignore Got it. Found Contributing.MD which tells about it :)

**Comment by jdneo** [comment]
> Oh.. okay.. no issues.. Im new to these contributions. Just forking the repository, making the relevant changes and testing .. raising merge requests .. is this the process or if you have any relevant documentation, i can look into it.. thanks in advance.. :)

Yes, it is :)

BTW, we are working on some refactoring so the latest contributing guide is here: https://github.com/microsoft/vscode-gradle/pull/1528

Please let me know if there is any problem during setup.

**Comment by skaluva** [comment]
Hi @jdneo , while working on this.. i found interesting thread which states about this issue and mentioned as resolved.
https://github.com/redhat-developer/vscode-java/issues/1169
I'm confused .. it looks different extension (**vscode-java** not **vscode-gradle**)
![image](https://github.com/user-attachments/assets/c24f4387-9abe-442e-ade9-91985ef7aa23)
Please have a look when you get sometime.

**Comment by jdneo** [comment]
The PR mentioned above is about import gradle project into Java language server. This issue is about the gradle server from this extension, consume the setting to run gradle tasks.

TBH, now I'm not confident about the correctness of this behavior. Since the setting name is called `java.import.xxx`. Is it correct to consume it when running gradle tasks? Should we introduce new settings?

**Comment by skaluva** [comment]
I think its valid to honor `java.import.gradle.arguments` for gradle command. Because you are honoring "java.import.xxx" settings for gradle tasks while running for example, `java.import.gradle.jvmArguments` ,`java.import.gradle.user.home` etc before executing gradle commands.  In `vscode-java` extension's ReadMe document, it clearly says these are meant to pass to "gradle" only:
![image](https://github.com/user-attachments/assets/270aa446-4438-4b8b-b471-dc9f057335cb)

So i believe we should honor them without any new setting :)

**Comment by skaluva** [comment]
I made relevant changes, but im not sure how to test. As per contributing doc, i see these steps:

1) Run vscode launch configuration Debug Extension & Gradle Plugin.
2) Run vscode launch configuration Attach to Gradle Plugin.

I hope these two steps are meant for `vscode-gradle` project itself but not for my actual project where i would want to see these params are getting passed or not:

I ran those 2 steps in `vscode-gradle` but when i loaded my project in another window, its still loading marketplace extension only but not my extension code where i made changes. I think i'm missing something. Can you help ?

**Comment by Jiaaming** [comment]
> I made relevant changes, but im not sure how to test. As per contributing doc, i see these steps:
> 
> 1. Run vscode launch configuration Debug Extension & Gradle Plugin.
> 2. Run vscode launch configuration Attach to Gradle Plugin.
> 
> I hope these two steps are meant for `vscode-gradle` project itself but not for my actual project where i would want to see these params are getting passed or not:
> 
> I ran those 2 steps in `vscode-gradle` but when i loaded my project in another window, its still loading marketplace extension only but not my extension code where i made changes. I think i'm missing something. Can you help ?

Hi, these steps are for debugging code in [`gradle-plugin`](https://github.com/Jiaaming/vscode-gradle/tree/develop/gradle-plugin) folder (If you made changes to this folder, you might need to use these steps.). 
How about trying to run `Debug Extension`? It allow you to debug and set breakpoint in [`extension`](https://github.com/microsoft/vscode-gradle/tree/8e6e7ac008dd300ef18635ac140dad6f44a9bb0f/extension) module. 

Let me know if you have further questions.
