### ISSUE TITLE
can't load local installation

### ISSUE THREAD

**Issue by Phascolarctos** [microsoft/vscode-gradle#1615]
Extension Name: vscode-gradle
Extension Version: 3.16.4
OS Version: 
版本	Windows 11 专业版
版本号	23H2
操作系统版本	22631.4249
体验	Windows Feature Experience Pack 1000.22700.1041.0

VSCode version: 1.94.2

**Describe the bug**
java_home, gradle_home, gradle_user_home has been added to windows path.
when config the wrapper :  distributionUrl=file:///D:/EnvDev/gradle-8.10.2-all.zip
it happens this: 
always Initializing Gradle Language Server
Couldn't start client Gradle Language Server

**To Reproduce**
Illegal char <:> at index 2:

**Expected behavior**
normal load gradle from local installation location

**Output from "Gradle for Java"**
[info] [gradle-server] Gradle Server started, listening on 14668
[info] [gradle-server] 10�� 11, 2024 6:09:10 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/EnvDev/gradle-8.10.2-all.zip
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.microsoft.gradle.resolver.GradleLibraryResolver.getWrapperPropertiesInfo(GradleLibraryResolver.java:202)
	at com.microsoft.gradle.resolver.GradleLibraryResolver.resolveGradleAPI(GradleLibraryResolver.java:111)
	at com.microsoft.gradle.resolver.GradleLibraryResolver.resolveGradleAPI(GradleLibraryResolver.java:103)
	at com.microsoft.gradle.GradleServices.applySetting(GradleServices.java:168)
	at com.microsoft.gradle.GradleLanguageServer.initialize(GradleLanguageServer.java:76)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 13 more
[info] [gradle-server] 10�� 11, 2024 6:09:10 ���� org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
����: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: �ܵ��ѽ�����
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: �ܵ��ѽ�����
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:122)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: �ܵ��ѽ�����
	at com.microsoft.gradle.transport.NamedPipeStream$NamedPipeInputStream.read(NamedPipeStream.java:146)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	... 6 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: �ܵ��ѽ�����
	at java.base/sun.nio.ch.PendingFuture.get(PendingFuture.java:183)
	at com.microsoft.gradle.transport.NamedPipeStream$NamedPipeInputStream.read(NamedPipeStream.java:136)
	... 7 more
Caused by: java.io.IOException: �ܵ��ѽ�����
	at java.base/sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:299)
	at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	... 3 more
[info] Gradle client connected to server
[info] Java Home: D:\EnvDev\jdk-21.0.4+7
[info] JVM Args: --add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant
[info] Gradle User Home: E:\gradle
[info] Gradle Version: 8.10.2

**Does the bug still exist if you disable all other extensions?**
Yes

**Comment by Phascolarctos** [comment]
[RFC 2732](https://www.ietf.org/rfc/rfc2732.txt)
### Reason
> the character ':' unicode is \u003a, it is out of condition range.
```java
private static final boolean isInvalidPathChar(char ch) {
        return ch < '\u0020' || reservedChars.indexOf(ch) != -1;
}
```
### Resolution
before your driverletter, ':' encode URI is %3A
> file:///D%3A/filepath
