### ISSUE TITLE
Gradle Wrapper on FTP

### ISSUE THREAD

**Issue by Slay3r** [microsoft/vscode-gradle#695]
Extension Name: vscode-gradle
Extension Version: 3.4.5
OS Version: Windows 10 (17763.1397)  x64
VSCode version: 1.48.2
Java: 11
Gradle: 6.6.1

**Describe the bug**
After changing the distributionUrl for the wrapper to a local location or ftp, the build will not work anymore.
The wrapper zip is successfully downloaded and also unpacked in the userprofile (.gradle/wrapper/dists).
`[error] [gradle-server] Could not fetch model of type 'GradleProject' using Gradle distribution`

I work behind a restricted company firewall and therefore I try to get the wrapper over the intranet

**To Reproduce**
Change distributionUrl in gradle-wrapper.properties to a local or ftp destination.
Save and the error will pop up (Gradle: Build Error).
Close and Reopen will produce the same.

**Expected behavior**
I want to tell gradle to get and use the wrapper from a ftp, because of the restricted firewall.
In fact the download and unzip is working but the build is not.
Maybe I have to include something on my ftp?

**Screenshots**
![gradle tasks](https://user-images.githubusercontent.com/6098527/93047747-73001c80-f65d-11ea-871e-c5a2bc8cdfd9.jpg)
![gradle-wrapper](https://user-images.githubusercontent.com/6098527/93047748-74314980-f65d-11ea-8d18-0591d5e94ed7.jpg)

**Output from "Gradle Tasks"**
`[info] [gradle-server] Server started, listening on 52714
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\Java\jdk-11.0.2
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\user\.gradle
[info] Gradle Version: 6.6.1
[error] [gradle-server] Could not fetch model of type 'GradleProject' using Gradle distribution 'https://eu.artifactory.de/artifactory/gradle/distributions/gradle/gradle-6.6.1-bin.zip'.
[error] Error getting build for d:\project: Could not fetch model of type 'GradleProject' using Gradle distribution 'https://eu.artifactory.de/artifactory/gradle/distributions/gradle/gradle-6.6.1-bin.zip'.
[info] Found 0 tasks
[info] Java Home: C:\Program Files\Java\jdk-11.0.2
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\user\.gradle
[info] Gradle Version: 6.6.1
[error] [gradle-server] Could not fetch model of type 'GradleProject' using Gradle distribution 'https://eu.artifactory.de/artifactory/gradle/distributions/gradle/gradle-6.6.1-bin.zip'.
[error] Error getting build for d:\project: Could not fetch model of type 'GradleProject' using Gradle distribution 'https://eu.artifactory.de/artifactory/gradle/distributions/gradle/gradle-6.6.1-bin.zip'.
[info] Found 0 tasks
[info] [gradle-server] Sep. 14, 2020 7:36:32 VORM. io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@1c5f1351
java.lang.IllegalArgumentException: No enum constant com.github.badsyntax.gradle.DaemonInfo.DaemonStatus.UNKNOWN
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.github.badsyntax.gradle.DaemonInfo$DaemonStatus.valueOf(DaemonInfo.java:107)
	at com.github.badsyntax.gradle.DaemonStatus.lambda$get$0(DaemonStatus.java:37)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.github.badsyntax.gradle.DaemonStatus.get(DaemonStatus.java:26)
	at com.github.badsyntax.gradle.handlers.GetDaemonsStatusHandler.run(GetDaemonsStatusHandler.java:34)
	at com.github.badsyntax.gradle.GradleService.getDaemonsStatus(GradleService.java:45)
	at com.github.badsyntax.gradle.GradleGrpc$MethodHandlers.invoke(GradleGrpc.java:633)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [gradle-server] Sep. 14, 2020 7:36:32 VORM. io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@1b14172b
java.lang.IllegalArgumentException: No enum constant com.github.badsyntax.gradle.DaemonInfo.DaemonStatus.UNKNOWN
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.github.badsyntax.gradle.DaemonInfo$DaemonStatus.valueOf(DaemonInfo.java:107)
	at com.github.badsyntax.gradle.DaemonStatus.lambda$get$0(DaemonStatus.java:37)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.github.badsyntax.gradle.DaemonStatus.get(DaemonStatus.java:26)
	at com.github.badsyntax.gradle.handlers.GetDaemonsStatusHandler.run(GetDaemonsStatusHandler.java:34)
	at com.github.badsyntax.gradle.GradleService.getDaemonsStatus(GradleService.java:45)
	at com.github.badsyntax.gradle.GradleGrpc$MethodHandlers.invoke(GradleGrpc.java:633)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Unable to get daemon status: 2 UNKNOWN: 
[info] [gradle-server] Sep. 14, 2020 7:36:32 VORM. io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@22c3d184
java.lang.IllegalArgumentException: No enum constant com.github.badsyntax.gradle.DaemonInfo.DaemonStatus.UNKNOWN
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.github.badsyntax.gradle.DaemonInfo$DaemonStatus.valueOf(DaemonInfo.java:107)
	at com.github.badsyntax.gradle.DaemonStatus.lambda$get$0(DaemonStatus.java:37)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.github.badsyntax.gradle.DaemonStatus.get(DaemonStatus.java:26)
	at com.github.badsyntax.gradle.handlers.GetDaemonsStatusHandler.run(GetDaemonsStatusHandler.java:34)
	at com.github.badsyntax.gradle.GradleService.getDaemonsStatus(GradleService.java:45)
	at com.github.badsyntax.gradle.GradleGrpc$MethodHandlers.invoke(GradleGrpc.java:633)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Does the bug still exist if you disable all other extensions?**
Yes, I disabled all other extensions.

**Comment by badsyntax** [comment]
Just to confirm, are you able to run a gradle build using the wrapper script outside of vscode?

**Comment by Slay3r** [comment]
Hi @badsyntax,
If the wrapper is installed successfully with the default distributionUrl, then it works in and outside of vscode.
After changing the url to the ftp location it starts downloading and the wrapper gets unzipped but it doesn't work in or outside of vscode. 
So I guess its not a fault of the vscode plugin.

But I don´t know why it doesn't work.

**Comment by Slay3r** [comment]
Hi @badsyntax,
If the wrapper is installed successfully with the default distributionUrl, then it works in and outside of vscode.
After changing the url to the ftp location it starts downloading and the wrapper gets unzipped but it doesn't work in or outside of vscode. 
So I guess its not a fault of the vscode plugin.

Thanks for your time!
